services:
  # This defines your frontend static site
  - type: static_site
    name: gganbu-go-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    publishDir: dist
    rewrites:
      - source: /*
        destination: /index.html
    envVars:
      - key: VITE_SOCKET_URL
        # This automatically gets the URL from your backend service below
        fromService:
          type: web
          name: gganbu-go-backend
          property: url

  # This defines your backend web service
  - type: web
    name: gganbu-go-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: REDIS_URL
        # This syncs the secret from your Upstash database
        sync: false 
      - key: CORS_ORIGIN
        # This automatically gets the URL from your frontend service above
        fromService:
          type: static_site
          name: gganbu-go-frontend
          property: url